### PR TITLE
Account for Multi Monitor Setups (Was expanding the app across all three screens)

### PR DESCRIPTION
**Pull request by MattRay0295**
Bug - Multi Monitor setup had the application expanding 3 monitors
Fix - Account for a multi monitor setup (My coding in powershell is rough but it does work and tested multiple times)

### CODE REVIEW

**Comment by LeDragoX** [comment]
Hello, thanks for the contribution.
I need to state 2 things, sorry for the incovenience.
- This is sending to the `main` branch, there's a `develop` branch just for that ([CONTRIBUTING.md](https://github.com/LeDragoX/Win-Debloat-Tools/blob/main/CONTRIBUTING.md)).
- The file which should be modified to get the resolution is a self-made lib, [here](https://github.com/LeDragoX/Win-Debloat-Tools/blob/main/src/lib/ui-helper.psm1#L12).

Based on your idea, i think i got a definitive solution (i'll test today), thanks, and sorry cause i'll close your PR. I'll try to make you the co-author.

**Comment by LeDragoX** [comment]
You can test on development branch now

**Comment by MattRay0295** [comment]
@LeDragoX Whoops my bad, wasn't really paying attention and it was meant as a headstart for you, barely tinker with powershell but it seems you got it figured out and merged, have a good one glad I could help!

**Comment by MattRay0295** [comment]
> You can test on development branch now

That doesn't seem to work btw, the changes you did. 
It seems to be an issue with `Get-CurrentResolution` which is why I changed it to `Get-WmiObject -Class Win32_DesktopMonitor | ForEach-Object {$_.ScreenWidth, $_.ScreenHeight}`

Btw I have 3 monitors, Left and right at 32in LG 4ks and middle is Asus 27in 2k Gaming Monitor @LeDragoX

**Comment by LeDragoX** [comment]
This is what i did to get the correct resolution @MattRay0295.
There are 2 methods:
- One which happens with only 1 monitor;
- On the `Else` statement, when detects more than 1 monitor, or "none"
  - So it should take the screen with lower resolution as a parameter and use it.

_You can look at this file `/src/lib/ui-helper.psm1`_

```ps
    $NumberOfScreens = (Get-CimInstance -Class "Win32_VideoController" | ForEach-Object { "$_" }).Count
    $ScreenWidth = $null
    $ScreenHeight = $null

    If ($NumberOfScreens -eq 1) {
        # Accepts Scaling/DPI
        [System.Windows.Forms.SystemInformation]::VirtualScreen | ForEach-Object {
            If (!$ScreenWidth -or !$ScreenHeight) {
                $ScreenWidth = $_.Width
                $ScreenHeight = $_.Height
            }

            If (($_.Width) -and ($_.Width -le $ScreenWidth)) {
                $ScreenWidth = $_.Width
                $ScreenHeight = $_.Height
            }
        }
    } Else {
        # Doesn't accepts Scaling/DPI (rollback method)
        Get-CimInstance -Class "Win32_VideoController" | ForEach-Object {
            If (!$ScreenWidth -or !$ScreenHeight) {
                $ScreenWidth = $_.CurrentHorizontalResolution
                $ScreenHeight = $_.CurrentVerticalResolution
            }

            If (($_.CurrentHorizontalResolution) -and ($_.CurrentHorizontalResolution -le $ScreenWidth)) {
                $ScreenWidth = $_.CurrentHorizontalResolution
                $ScreenHeight = $_.CurrentVerticalResolution
            }
        }
    }
```

**Pull request closed without merging**
